"""create users, repositories, pr_scores, pr_snapshots tables

Revision ID: c42f9aaa9fb7
Revises: 
Create Date: 2026-07-07 11:42:42.389757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42f9aaa9fb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(), nullable=False),
    sa.Column('github_token_encrypted', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_username')
    )
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner', 'name', 'user_id', name='uq_repository_owner_name_user')
    )
    op.create_table('pr_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('score_level', sa.String(), nullable=False),
    sa.Column('score_points', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_score_id', sa.Integer(), nullable=False),
    sa.Column('lines_changed', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('days_open', sa.Integer(), nullable=False),
    sa.Column('touched_tests', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pr_score_id'], ['pr_scores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pr_score_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr_snapshots')
    op.drop_table('pr_scores')
    op.drop_table('repositories')
    op.drop_table('users')
    # ### end Alembic commands ###
